### ISSUE TITLE
Multiple compilation errors on OS X

### ISSUE THREAD

**Issue by sergiyprotsiv** [fmi-alg/libratss#7]
Hi, I'm trying to use libratss (as part of libdts2) and cannot properly compile it on Mac OS X.
Both clang and gcc-7 give multiple errors usually related to type conversions.

For example:
`In file included from /Users/s/libdts2/vendor/libratss/src/GeoCoord.cpp:1:
/Users/s/libdts2/vendor/libratss/include/libratss/GeoCoord.h:54:20: error: implicit instantiation of undefined template
      'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
inline std::string to_string(const LIB_RATSS_NAMESPACE::GeoCoord & sc) {

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:193:32: note: template is
      declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;`

Similar errors later occur in different places like CGAL/Conversion.cpp (where it complains about ambiguous templates for `mpq_class(v.numerator().get(), v.denominator().get());` and in other places.

Do you have a suggestion on how to compile libratss/libdts2 properly?

**Comment by dbahrdt** [comment]
I'm unfortunately only developing under linux. Which clang/gcc version are you using? Maybe I can reproduce this on a linux machine with the same compiler versions.

The first error looks like a missing include. Can you add 
```
#include <string>
```
to GeoCord.h.

Can you post the exact compiler errors for the other errors as well?

@krumpefp can you compile libdts2 on a recent gcc?

**Comment by krumpefp** [comment]
I freshly cloned and compiled the libratss project with
gcc (GCC) 8.1.1 20180531
clang version 6.0.0 (tags/RELEASE_600/final)
it compiles with no errors reported.

Same for the libdts2 project.

It seems like we need to dig into the exact compiler errors

**Comment by dbahrdt** [comment]
Fresh clone using:
gcc (Gentoo 7.2.0-r1 p1.1) 7.2.0
compiles without errors.

**Comment by sergiyprotsiv** [comment]
Hi, thanks, it compiles without errors on Ubuntu for me as well.
I have tried both Apple's clang and the official clang-6.0.0, as well as gcc-7. All of them give the errors.

First, the one from GeoCoord:

```
[ 35%] Building CXX object libratss/CMakeFiles/ratss.dir/src/GeoCoord.cpp.o
clang-6.0: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]
clang-6.0: warning: optimization flag '-frounding-math' is not supported [-Wignored-optimization-argument]
In file included from /Users/seriozha/libdts2/vendor/libratss/src/GeoCoord.cpp:1:
/Users/seriozha/libdts2/vendor/libratss/include/libratss/GeoCoord.h:54:20: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
inline std::string to_string(const LIB_RATSS_NAMESPACE::GeoCoord & sc) {
                   ^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/iosfwd:193:32: note: template is
      declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from /Users/seriozha/libdts2/vendor/libratss/src/GeoCoord.cpp:1:
/Users/seriozha/libdts2/vendor/libratss/include/libratss/GeoCoord.h:55:9: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
        return LIB_RATSS_NAMESPACE::to_string(sc);
               ^
/Users/seriozha/libdts2/vendor/libratss/include/libratss/constants.h:5:29: note: 
      expanded from macro 'LIB_RATSS_NAMESPACE'
#define LIB_RATSS_NAMESPACE ratss
                            ^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/iosfwd:193:32: note: template is
      declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from /Users/seriozha/libdts2/vendor/libratss/src/GeoCoord.cpp:3:
/Users/seriozha/libdts2/vendor/libratss/include/libratss/SphericalCoord.h:54:15: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
inline string to_string(const LIB_RATSS_NAMESPACE::SphericalCoord & sc) {
              ^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/iosfwd:193:32: note: template is
      declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from /Users/seriozha/libdts2/vendor/libratss/src/GeoCoord.cpp:3:
/Users/seriozha/libdts2/vendor/libratss/include/libratss/SphericalCoord.h:55:9: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
        return LIB_RATSS_NAMESPACE::to_string(sc);
               ^
/Users/seriozha/libdts2/vendor/libratss/include/libratss/constants.h:5:29: note: 
      expanded from macro 'LIB_RATSS_NAMESPACE'
#define LIB_RATSS_NAMESPACE ratss
                            ^
/usr/local/Cellar/llvm/6.0.0/include/c++/v1/iosfwd:193:32: note: template is
      declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
```

Adding `#include <string>` to GeoCoord.h and SphericalCoord.h fixes this issue.

But then I get the "ambiguous conversion errors", for which I tried some ad-hoc fixes that do not work properly:

```
[ 35%] Building CXX object libratss/CMakeFiles/ratss.dir/src/CGAL/Conversion.cpp.o
clang-6.0: warning: optimization flag '-ffat-lto-objects' is not supported [-Wignored-optimization-argument]
clang-6.0: warning: optimization flag '-frounding-math' is not supported [-Wignored-optimization-argument]
/Users/seriozha/libdts2/vendor/libratss/src/CGAL/Conversion.cpp:39:34: error: conversion from 'CGAL::ExtendedInt64z::base_type' (aka 'long long') to
      'const mpz_class' (aka 'const __gmp_expr<__mpz_struct [1], __mpz_struct [1]>') is ambiguous
                return mpq_class(v.numerator().get(), v.denominator().get());
                                 ~~~~~~~~~~~~~~^~~~~
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
  __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
  ^
/usr/local/include/gmpxx.h:1403:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed char c) { init_si(c); }             \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1404:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned char c) { init_ui(c); }           \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1405:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed int i) { init_si(i); }              \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1406:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned int i) { init_ui(i); }            \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1407:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed short int s) { init_si(s); }        \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1408:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned short int s) { init_ui(s); }      \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1409:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed long int l) { init_si(l); }         \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1410:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned long int l) { init_ui(l); }       \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1411:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(float f) { init_d(f); }                    \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1412:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(double d) { init_d(d); }
  ^
/Users/seriozha/libdts2/vendor/libratss/src/CGAL/Conversion.cpp:77:34: error: conversion from 'CGAL::ExtendedInt64z::base_type' (aka 'long long') to
      'const mpz_class' (aka 'const __gmp_expr<__mpz_struct [1], __mpz_struct [1]>') is ambiguous
                return mpq_class(v.numerator().get(), v.denominator().get());
                                 ~~~~~~~~~~~~~~^~~~~
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
  __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS
  ^
/usr/local/include/gmpxx.h:1403:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed char c) { init_si(c); }             \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1404:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned char c) { init_ui(c); }           \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1405:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed int i) { init_si(i); }              \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1406:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned int i) { init_ui(i); }            \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1407:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed short int s) { init_si(s); }        \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1408:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned short int s) { init_ui(s); }      \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1409:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(signed long int l) { init_si(l); }         \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1410:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(unsigned long int l) { init_ui(l); }       \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1411:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(float f) { init_d(f); }                    \
  ^
/usr/local/include/gmpxx.h:1502:3: note: candidate constructor
/usr/local/include/gmpxx.h:1412:3: note: expanded from macro '__GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS'
  __gmp_expr(double d) { init_d(d); }
  ^
In file included from /Users/seriozha/libdts2/vendor/libratss/src/CGAL/Conversion.cpp:1:
In file included from /Users/seriozha/libdts2/vendor/libratss/include/libratss/Conversion.h:59:
In file included from /Users/seriozha/libdts2/vendor/libratss/include/libratss/CGAL/Conversion.h:13:
/Users/seriozha/libdts2/vendor/libratss/include/libratss/CGAL/ExtendedInt64q.h:965:10: error: call to constructor of
      'CGAL::ExtendedInt64q<CGAL::Gmpq>::extension_type' (aka 'CGAL::Gmpq') is ambiguous
                return extension_type(getPq().num, getPq().den);
                       ^              ~~~~~~~~~~~~~~~~~~~~~~~~
/Users/seriozha/libdts2/vendor/libratss/src/CGAL/Conversion.cpp:83:82: note: in instantiation of member function
      'CGAL::ExtendedInt64q<CGAL::Gmpq>::asExtended' requested here
        return Conversion<CGAL::ExtendedInt64q<CGAL::Gmpq>::extension_type>::toMpreal(v.asExtended(), precision);
                                                                                        ^
/usr/local/include/CGAL/GMP/Gmpq_type.h:139:3: note: candidate constructor
  Gmpq(int n, int d)
  ^
/usr/local/include/CGAL/GMP/Gmpq_type.h:149:3: note: candidate constructor
  Gmpq(signed long n, unsigned long d)
  ^
/usr/local/include/CGAL/GMP/Gmpq_type.h:155:3: note: candidate constructor
  Gmpq(unsigned long n, unsigned long d)
  ^
/usr/local/include/CGAL/GMP/Gmpq_type.h:161:3: note: candidate constructor
  Gmpq(const Gmpz& n, const Gmpz& d)
  ^
3 errors generated.
make[2]: *** [libratss/CMakeFiles/ratss.dir/src/CGAL/Conversion.cpp.o] Error 1
make[1]: *** [libratss/CMakeFiles/ratss.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dbahrdt** [comment]
This is very strange. It seems like there is no appropriate constructor taking an uint64_t. Do you happen to be on a 32 Bit system?

Update: I've added a check to Conversion.h.

**Comment by sergiyprotsiv** [comment]
No, definitely a 64-bit. 
When browsing the errors before, I think specifically did not like size_t and suggested that it could be cast to unsigned long, unsigned, etc. Maybe this also an issue with some header? I've tried adding stdlib.h (for size_t), but that did not help and I cannot really understand the template magic that is going on in CGAL/Conversion.

**Comment by dbahrdt** [comment]
Did you try the latest version (with the added check)? It may be the case that clang on Mac has `sizeof(signed long int) == 4`. You can try to add `#include <stdint.h>` to the files causing the problems.

**Comment by sergiyprotsiv** [comment]
Yes, tried this now (and adding `#include <stdint.h>` as well), gives the same issue.

I think I have found the issue and it actually lies with GMP. There is a macro
```#define __GMPXX_DEFINE_ARITHMETIC_CONSTRUCTORS		\
  __gmp_expr(signed char c) { init_si(c); }		\
  __gmp_expr(unsigned char c) { init_ui(c); }		\
  __gmp_expr(signed int i) { init_si(i); }		\
  __gmp_expr(unsigned int i) { init_ui(i); }		\
  __gmp_expr(signed short int s) { init_si(s); }	\
  __gmp_expr(unsigned short int s) { init_ui(s); }	\
  __gmp_expr(signed long int l) { init_si(l); }		\
  __gmp_expr(unsigned long int l) { init_ui(l); }	\
  __gmp_expr(float f) { init_d(f); }			\
  __gmp_expr(double d) { init_d(d); }
```

This only covers the 32-bit types (like `unsigned long`), though the discussion [here](https://groups.google.com/forum/#!topic/mpir-devel/SJA3wS3kitY) seems to imply that on Linux `unsigned long` is usually 64-bit. Mac has 32-bit unsigned long and the macro above does not define anything for `unsigned long long`. The discussion in the link is from 2011, but I have not found a resolution to the issue.

Thins might not be the root cause, but at least replacing 
`mpq_class(v.numerator().get(), v.denominator().get());` 
with 
`mpq_class((unsigned long)v.numerator().get(), (unsigned long)v.denominator().get());`
compiles fine. Putting `size_t` or `uint64_t` or `unsigned long long` results in the same compilation errors as before.

**Comment by dbahrdt** [comment]
That's exactly what I thought and why I added a check in 4be594b49902d780bf2655eca1ffb4924dc0f45a.
If this compiles, then the problem should be somewhere else. According to [wikipedia](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models) MacOS uses the LP64 data model where `long int` is 64 Bit wide.

**Comment by sergiyprotsiv** [comment]
Ok, sorry, I have misunderstood that. Well, if I replace (or cast) `uint64_t` to `unsigned long` in about 20 places across the code base, both libratss and libdts2 compile fine (and I imagine there will be no issues with them running since uint64_t and unsigned long are the same type).

Finally, in order to compile the dts2tools  etc, one needs to `#include <array>` in ProjectSN.h.

There are a bunch of other errors beyond that in triang.cpp (e.g. malloc_trim not available and the header for malloc being <malloc/malloc.h> instead of just <malloc.h>), but they seem to be inessential for the use of the library.

However, trying to use the library as part of an application results in further errors:
```
/Users/seriozha/libdts2/include/libdts2/Constrained_delaunay_triangulation_base_traits_s2.h:231:30: Rvalue reference to type '__gmp_expr<...>' cannot bind to lvalue of type '__gmp_expr<...>''
```

which refers to the "x" in `Conversion<FT>::moveFrom(x)` in
```
Point_3 operator()(const LIB_RATSS_NAMESPACE::GeoCoord & geoCoord) const {
			mpq_class x, y, z;
			m_proj.projectFromGeo(geoCoord.lat, geoCoord.lon, x, y, z, significands());
			return Point_3(
				Conversion<FT>::moveFrom(x),
				Conversion<FT>::moveFrom(y),
				Conversion<FT>::moveFrom(z)
			);
		}
```

Do you have any pointers on what might be an issue there?

**Comment by dbahrdt** [comment]
We're setting up a MacOS installation to reproduce this issue.

**Comment by dbahrdt** [comment]
I've fixed all compilation errors that I've encountered and hopefully the last one as well. Can you try the latest HEAD on master?

**Comment by sergiyprotsiv** [comment]
Thanks a lot! The library compiles fine now. triang.cpp does not compile due to the liker error with -lboost_thread (but that can of course be specific to my machine, I did not investigate further).

Importantly, I still cannot use the library in my own code due to the "Rvalue" errors I mentioned above. I am just trying to compile the sample code you have on the project's frontpage. Maybe the sample code is outdated (it still uses libdts instead of libdts2 in the header)? I have tried both Constrained_delaunay_triangulation_s2 and the simplest Delaunay_triangulation_s2 and they both give the errors above.

**Comment by dbahrdt** [comment]
I'm working on a fix for the linker error (rewrite the find cgal part). After that I'll look into the rvalue problem.

**Comment by dbahrdt** [comment]
I've pushed the fixes for the linker error. The rvalue error should be gone as well. If it is still there, can you post the exact compiler error and if possible a minimum working example.

Additionally, can you compile the tests and tools of libratss and libdts2?

I'm testing this on MacOS High Sierra with the default apple compiler:
```
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
```

Packages are installed using macports.

UPDATE: I've added the example from the readme to the examples folder. It also compiles on our machine.

**Comment by sergiyprotsiv** [comment]
Great, thanks, the example file compiles just fine. 
I still cannot get it to work from inside Xcode (only via cmake), but it appears that that is an issue with my system. Thanks a lot for your support!

**Comment by dbahrdt** [comment]
So far no more complaints :) Feel free to re-open if anything is still/again broken.
